### PR TITLE
Refactor tests (fix bug #14) and cast post model published_at property

### PR DESCRIPTION
**Pull request by erikgall**
I was testing out your application and thought what you had was great, **simple** start. I attempted to run the tests and encountered bug #14. Which led me down the road of digging into your tests, and some other parts of your codebase pretty thoroughly. 

To run your tests (with my fix) make sure you have created a `canvas_testing` database first. This will eliminate bug #14. 

### What did I do
I updated the way you were logging in your the user in your tests and created a user model factory for testing purposes as well. For every test you were repeating the same assertions (userLogin()). Laravel provides some nice test helpers such as the `actingAs` method so you can skip right to the point of the authenticated test. There were also a few places you could use things shortcuts such as `seeIsAuthenticated(As)` methods, etc. 

I also created a `InteractsWithDatabase` trait that uses the Laravel `DatabaseTransactions` trait. You will also see that I copied over and changed the `runDatabaseMigrations` method from the `DatabaseMigrations` trait... I changed it to reset the database migrations after each test to prevent an error caused by the migrations not being run when they should.

Last but not least.. I also added the the published_at field to the dates array in the Post model. This means when you call `$post->published_at`, it will already be casted to a Carbon instance. In turn, I updated the `index.blade.php` view to use the published_at Carbon instance.

Thanks,

Erik

### CODE REVIEW

**Comment by talv86** [comment]
Great work! the current bug has been doing my head in, can't wait for this to get merged in! :+1:

**Comment by austintoddj** [comment]
Awesome! Thanks for the contribution. Quick thought: is there a way we can do this with only 1 database? I'm not aware of it, but just wanted to think of the easiest process for others to get the application up and running. If not, perhaps we just add a step in the readme to create `canvas_testing` prior to running unit tests. What do you think?

**Comment by Padarom** [comment]
I think if people want to get the application running as quickly as possible they don't even need to run the tests at all, that should be done for them by your CI before release of new versions. If I remember correctly there's an issue with SQLite support at the moment (though I don't remember the exact error I was getting trying to set it up), but if a secondary database is a concern, you could just run it on a temporary sqlite database (once that's supported).

**Comment by Padarom** [comment]
Just re-installed the application, I posted the issue with sqlite in #22.

**Comment by talv86** [comment]
:+1: for the sqlite solution if possible

**Comment by austintoddj** [comment]
@erikgall Looks like an error shows up now when saving posts. Thoughts?

screen shot 2016-07-07 at 10 53 10 am

**Comment by talv86** [comment]
at a glance, maybe its cause the date is coming in with "/" separators and the carbon object is looking for "-" separators. I did find it weird that it wasn't using hyphens when I added the date time picker widget but it seemed to be working. Should be easy to fix by updating the JS on the edit and create blade files for posts.

**Comment by austintoddj** [comment]
You're the man @talv86. Fixed with commit: c6289bf3e26bfb3cf5acb0dcc3e9a9cf6bbc7d96

**Comment by erikgall** [comment]
Thank you @austintoddj and @talv86 (great catch on the Carbon fix btw)

I'm glad I finally saw/took the opportunity to contribute to an open source project.

@Padarom I saw the bug (#22) you posted...  I came across this late last night when I was putting this PR together. My fix for it was just adding ->nullable() at the end of each line that added a new column. If your defaulting each column to an empty string, it can change how you test if something is set... I use nullable and if I'm testing if a model has a non empty property/column, I do the following:
```php 
if ($model->column) {
// do something if the column/property is not null
}
```
and that if statement wont execute if null.

**Comment by erikgall** [comment]
@austintoddj I'm not aware of a way to do it with one database. The norm that I've always used and seen  has been 2 databases. In the Laravel world, I would say it is most common to use 2 databases, with the testing DB being a sqlite in memory database. In the Rails world, I would say 2 databases named like I've purposed/based on environment is the most common. 

I've run into problems using SQLite, like the one discussed earlier. So, I usually just create a second database of the type I'm using. Ex. When I was doing this stuff last night I created 2 Postgres databases `canvas` and `canvas_testing` and no headaches.

**Comment by Padarom** [comment]
@erikgall I thought about that as well, but PHP evaluates [empty strings as `false`](http://php.net/manual/en/language.types.boolean.php#language.types.boolean.casting), so this should not be an issue if you're just testing if the value is evaluated as true or false. It is however an issue, if you're checking with `is_null` instead.

**Pull request merged**
