### PR TITLE
New lang: bg. Updated lang: ru. URL slug ability to group by lang.

### PR DESCRIPTION
**Pull request by thewwwizard**
- Added new language - Bulgarian.
- Updated language - Russian.
- Ability to add different language sets for URL slugify funtion.
Group sets by lang is required cause some langs may have their own rules for the same symbols (like "Щ" in ru and bg - lines 81 and 116).
Not a perfect solution with slug but in this case I found it the easiest one :)
More info in the commit description..

### CODE REVIEW

**Comment by austintoddj** [comment]
Thanks for submitting this @thewwwizard! I'll take a look at this in just a bit.

**Review by austintoddj — CHANGES_REQUESTED** [review]
So after looking at this a bit, I wonder if we could leave the `strings.js` file as it is right now, and only merge in the 2 language file changes.

Then, let's do a separate PR since I want to try and find a more future-proof solution to this `slugify()` method. You can certainly add this code you've written into that new PR, but I want to explore other ways we can approach it as well.

**Comment by thewwwizard** [comment]
@austintoddj Ok. So I'll create a separate PR with only these 2 commits (lang file changes). And do I need to change anything in the current PR?

**Comment by austintoddj** [comment]
No you should be good. Once that new PR is merged in with the language changes, the only change in this one will be the slugify() method.

**Review by austintoddj — APPROVED** [review]

**Pull request merged**
