### PR TITLE
Authentication

### PR DESCRIPTION
**Pull request by foxted**
Change on authentication according to issue #152

### CODE REVIEW

**Comment by austintoddj** [comment]
Awesome, thanks so much for tackling this. You're the man @foxted!

**Comment by foxted** [comment]
@austintoddj You're welcome. We have 5 controllers instead of 4 as Canvas has a PasswordController used to change password in the backend. 

About issue #148, do you just want the regular password reset feature?

**Comment by austintoddj** [comment]
Great, thanks for letting me know, that makes sense. 

And yes, I believe the default Laravel reset password feature would be perfect. Just needed a way for users to be able to have another way in without manually touching the database.

**Comment by austintoddj** [comment]
If you want to make that another PR, I can merge this one in right away.

**Comment by foxted** [comment]
Yep, I'll make another PR

**Comment by austintoddj** [comment]
@foxted Ok, this may be just being too picky, but is there a way to block the `auth/login` route altogether? It's not that big of a deal really, just OCD tendencies coming through. If not, then what you have here is perfect because it all works fine. But if it's possible to not even have the `auth/login` route work at all, that'd be preferential.

**Comment by foxted** [comment]
@austintoddj I just saw your comment!

- Created password reset feature (didn't write any tests as it is close to Laravel core features, I figured they are already tested)
- Get rid of `/auth/login`

**Comment by austintoddj** [comment]
Awesome @foxted. Thank you for your work. This should essentially close out #152 correct?

**Comment by foxted** [comment]
And #148

**Comment by austintoddj** [comment]
Perfect. Thanks again! Merging now..

**Pull request merged**
