### PR TITLE
Replaced tntsearch with the laravel scout tnt driver

### LINKED ISSUE #195: TNTSearch Laravel Scout Driver
@nticaric 
Ran into a bug recently in which when I save/update a post or tag, the index is not running. It wasn't until I ran the console command `canvas:index` that it actually updated the index. So my question is, are we running the index correctly after any post/tag interaction on the site?

Here is what it looked like running the console command manually:
screen shot 2016-09-30 at 6 31 52 am

### PR DESCRIPTION
**Pull request by talvbansal**
Should fix #195 since its using a native laravel implementation now

Whilst a new `.env` file variable _can_ be set to override the search driver should the user want to use another search provider, by default it'll default to **tntsearch** even if the `.env` file hasn't been updated.

There should no breaking changes with this patch

### CODE REVIEW

**Comment by austintoddj** [comment]
Thanks for doing this @talvbansal! Does this mean that the application will no longer write the `tags.index` and `posts.index` files? Or does that still work the same?

**Comment by talvbansal** [comment]
Its literally exactly the same since the same backend driver is used, this just automatically updates the index files when new items are added or updated. :)

**Comment by austintoddj** [comment]
So the only thing that concerns me is that the unit tests take almost 5x the amount of time to complete as before. They used to take roughly 6-7 seconds, now they average about 25 seconds. Not sure if somehow this PR is affecting their routines. Thoughts?

**Comment by talvbansal** [comment]
Wow, i hadn't even noticed! Mine just took 6mins to run!! When i was testing these models in Easel i didn't get this sort of slow down, any idea what you might be doing differently?

**Comment by austintoddj** [comment]
@talvbansal Not sure at this point. I know that @RDelorier and @erikgall have some good experience in PHPUnit testing, perhaps they can offer some insight?

**Comment by RDelorier** [comment]
If you're updating the index on every model save then the migrations will probably cause that to run a lot, you can disable the auto indeed in test mode to help speed it up

**Comment by RDelorier** [comment]
You can also try switching TNT database to in memory, check the phpunit.xml for an example of :memory:

**Comment by RDelorier** [comment]
```
Fatal error: Uncaught ReflectionException: Class log does not exist in /Users/rdelorier1/Repos/canvas/vendor/laravel/framework/src/Illuminate/Container/Container.php:734
Stack trace:
#0 /Users/rdelorier1/Repos/canvas/vendor/laravel/framework/src/Illuminate/Container/Container.php(734): ReflectionClass->__construct('log')
#1 /Users/rdelorier1/Repos/canvas/vendor/laravel/framework/src/Illuminate/Container/Container.php(629): Illuminate\Container\Container->build('log', Array)
#2 /Users/rdelorier1/Repos/canvas/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(697): Illuminate\Container\Container->make('log', Array)
#3 /Users/rdelorier1/Repos/canvas/vendor/laravel/framework/src/Illuminate/Container/Container.php(849): Illuminate\Foundation\Application->make('log')
#4 /Users/rdelorier1/Repos/canvas/vendor/laravel/framework/src/Illuminate/Container/Container.php(804): Illuminate\Container\Container->resolveClass(Object(ReflectionParameter))
#5 /Users/rdelorier1/Repos/canvas/vendor/laravel/framework/src/Illumina in /Users/rdelorier1/Repos/canvas/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 734
PHP Fatal error:  Uncaught ReflectionException: Class log does not exist in /Users/rdelorier1/Repos/canvas/vendor/laravel/framework/src/Illuminate/Container/Container.php:734
Stack trace:
#0 /Users/rdelorier1/Repos/canvas/vendor/laravel/framework/src/Illuminate/Container/Container.php(734): ReflectionClass->__construct('log')
#1 /Users/rdelorier1/Repos/canvas/vendor/laravel/framework/src/Illuminate/Container/Container.php(629): Illuminate\Container\Container->build('log', Array)
#2 /Users/rdelorier1/Repos/canvas/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(697): Illuminate\Container\Container->make('log', Array)
#3 /Users/rdelorier1/Repos/canvas/vendor/laravel/framework/src/Illuminate/Container/Container.php(849): Illuminate\Foundation\Application->make('log')
#4 /Users/rdelorier1/Repos/canvas/vendor/laravel/framework/src/Illuminate/Container/Container.php(804): Illuminate\Container\Container->resolveClass(Object(ReflectionParameter))
#5 /Users/rdelorier1/Repos/canvas/vendor/laravel/framework/src/Illumina in /Users/rdelorier1/Repos/canvas/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 734
```
well shit

**Comment by RDelorier** [comment]
zzz had to do `composer update` instead of `composer install`

**Comment by talvbansal** [comment]
I found a way for the scout driver to be set to null in testing mode but its just as slow as before :\

**Comment by RDelorier** [comment]
I can get the tests to speed up but it's going to take a little work, I'll do it as a separate pill request tho

**Comment by erikgall** [comment]
As @RDelorier said, the more times you touch/have to use the database the slower your tests are going to be. That is why in my eloquent-phpunit package I allow you to turn off database seeding, which makes the tests run around 3x faster.

**Comment by abhishek619** [comment]
there must be seperate pill requests

**Comment by abhishek619** [comment]
conflicting files must be recreated

**Comment by Jeroen-G** [comment]
Could it be possible to implement Scout, but let the user choose the driver?

**Comment by talvbansal** [comment]
@Jeroen-G absolutely, we're just shipping with TNTSearch out of the box so that everyone can use it initially with no need for access to a third party. 

To change the scout driver just change the `SCOUT_DRIVER` value in your projects .env file.

I haven't forgotten about this PR. I'm hoping to find time to amend the code as per Taylors recommendation [here](https://twitter.com/laravelphp/status/783425825638973440)

**Comment by talvbansal** [comment]
Forgot to comment on this, the issue with slow unit tests should be resolved now!

**Comment by austintoddj** [comment]
Awesome thanks @talvbansal!

**Comment by austintoddj** [comment]
@talvbansal Question about the `composer.json` file. If we are using Scout/TNT search driver, do we need the original TNT search package to still be pulled in? Or is this a drop-in replacement?

**Comment by talvbansal** [comment]
Ahh good spot, it should be able to be removed with no side effects the scout driver will automatically pull the package in as a dependency 😀

**Comment by talvbansal** [comment]
Done! :)

**Comment by austintoddj** [comment]
@talvbansal 2 things I noticed when pulling this down locally:

1. The sidebar navigation is gone on the `admin/post/create` page, not sure if other places as well

screen shot 2016-10-21 at 7 42 02 am


2. On the Tools page, there is a Reset Index function so that users can manually reset the index if they so choose. It throws a Scout error, wonder if you could look into that?

After that, I think it's ready to merge!

**Comment by talvbansal** [comment]
Not sure why the blank bar on the screen shot has happened, it works fine for me, have some of your assets been cached? If you clear them do you get the same issue?

So I looked into the reset index issue for scout and came across this within the scout code base:
```        
    if ($this->app->runningInConsole()) {
            $this->commands([
                ImportCommand::class,
                FlushCommand::class,
            ]);
    ....
```

So those artisan commands are only registered when the application is running on the console. Which to me makes sense since they're so infrequently used that it makes no sense to register them for every request.

At this point since scout is a first party laravel product and we've opened up the option for multiple drivers to be used as a result of its integration the question becomes: is having the reset index tool one that is likely to be used a lot? 

Models are auto indexed when they're updated now so the only reasonable case i can think for this is if you suffered some form of index corruption. If that were the case im sure you'd be on the command line trying to work out whats wrong anyway.

Just my thoughts on this.

**Comment by Jeroen-G** [comment]
I think you can fire console commands from a http app. Not sure how, but have seen it somewhere.

**Comment by talvbansal** [comment]
You can make artisan calls but only if the commands are registered, the above code shows that the commands are only registered when the app is run in the console.

But realistically how many people have reset indexes from the front end

**Comment by austintoddj** [comment]
@talvbansal Yup I do agree with you on that. It's probably very uncommon, I can take it out, especially if it's going to be happening automatically. For some reason still running into the blank sidebar issues, and also some JS stuff not working. Tried clearing out the asset caches, re-compiling everything but the issues still remain.

**Comment by talvbansal** [comment]
Sorry i was testing this out on another branch im working on, you're totally right, fixed in the latest commit and the references to resetting the index has been removed along with the unit test for it.

**Comment by austintoddj** [comment]
Awesome @talvbansal thanks for pushing all those commits. I think the internet is broken today because of all the DDOS attacks, so my merging this in may wait till everything is a little more stable. But really great work 👍

**Pull request merged**
