### PR TITLE
add support for fulltext search

### PR DESCRIPTION
**Pull request by nticaric**
The Material-Design-Iconic-Font.woff2 font file was missing

### CODE REVIEW

**Comment by nticaric** [comment]
This pull request adds full text search support. It searches among the tags and posts table.
Before the search is available, the command `php artisan index:posts` needs to be run.
After adding, deleting or updating posts/tags, the index will be automatically updated.

The results are sorted by relevance. Please try it out and let me know what you think

**Comment by austintoddj** [comment]
Looks great so far @nticaric, would you be able to take a look at the conflict and then I can merge this in today?

**Comment by stokic** [comment]
The search package uses sqlite for it's index files which makes it really fast, so that's why it's a requirement, but the data can be indexed from other sources of course. Currently it supports MySQL, pgSQL, SQLite and even plain txt files :)

So bottom line is, sqlite is a requirement for it to work it's magic, but the data source is totally flexible.

**Comment by austintoddj** [comment]
Thanks @stokic!

**Comment by nticaric** [comment]
@austintoddj here you go, the conflicts are resolved, in the meanwhile something was added to composer.json.

What about the command name, currently it's called `php artisan index:pots`, I am also thinking about `php artisan index:blog` because the indexed tables are posts and tags

**Comment by austintoddj** [comment]
Thanks @nticaric. Yeah in the meantime I added something to `composer.json` and made an installation command. Any way you can update your command name to be consistent with the installation one? i.e.. `canvas:COMMAND `

**Comment by nticaric** [comment]
great, the command name is now `canvas:indexer` and it will run also after the setup is done, so the user doesn't have to run it manually

**Pull request merged**
