### PR TITLE
added version function to gulpfile via elixir

### PR DESCRIPTION
**Pull request by Naoray**
I recently had an issue with updating my `CSS`. I modified some `SCSS` files and run `gulp` but it was not reflected in my browser (was using chrome).

I couldn't resolve the issue, so I thought it could be a cache issue...

After adding the `version()` function of `elixir` changes were reflected instantly.

### CODE REVIEW

**Comment by talvbansal** [comment]
@Naoray hey can you explain further what version does? I've not come across it before I'd love to know more!

**Comment by Naoray** [comment]
First of all... sorry I somehow got mixed up with my other PR regarding the title. (changed it now)

@talvbansal take a look at the official documentation of [elixir](https://laravel.com/docs/5.3/elixir#versioning-and-cache-busting). Basically it creates a `build` directory within the `public/` and appends a unique hash to the versioned filename. So the browser does not look for `css/frontend.css` anymore but instead for e.g. `build/css/frontend-a1b2f87080.css`. So every time you change your styles and call `gulp` afterwards, the browser loads the styles from a new resource.

In your `blade` files the assets are now loaded with `elixir('css/frontend.css')` instead of `assets('css/frontend.css')`.

The *'downside'* I've noticed is that there can only be one call for the `version()` function. Otherwise the previous one get's kinda otherwritten...

Hope my explanation was somehow useful...?

**Comment by austintoddj** [comment]
@Naoray From my experience with this, I've seen JS/CSS both get versioned. Is that something we could/should do here?

Small example from a previous project:

```php
elixir(function(mix) {
	mix.sass('main.scss')
	.scripts([
		'bootstrap.min.js'
	],'public/js/vendor.js','resources/assets/js')
	.scriptsIn('resources/assets/js/app','public/js/all.js')
	.version(['css/main.css','js/vendor.js', 'js/all.js']);
});
```

**Comment by Naoray** [comment]
@austintoddj yes, guess we should do this. Just have to look where all the js files are referenced in the blade partials.

**Comment by austintoddj** [comment]
@Naoray Yes you're right. They should be right alongside the css files I believe, for both the frontend and the backend. If you're unsure of where to look however I can get you full paths.

**Comment by Naoray** [comment]
included js versioning in `gulpfile`. Also searched for the references and ^replaced the `asset` with the `elixir` function.

There is also the possibility to version the images if needed.

Also we should consider moving the `assets` in the `public/` folder into an `public/assets` folder. At least for me it seems a bit 'unstructured'... 

now:
* public/
  * build/
  * css/
  * fonts/
  * js/
  * vendor/

would be nicer if it is just like:
* public/
  * build/
  * assets/

don't you think?

**Comment by austintoddj** [comment]
@Naoray Yup I agree. If you want to restructure it to streamline it and clean it up, by all means do so. As long as nothing breaks, I'm all for improving this. 👍

**Comment by Naoray** [comment]
Before I tackle this task: how are the images loaded into the public folder?

**Comment by austintoddj** [comment]
@Naoray Since I wanted to keep the app size as minimal as possible, I only wanted one copy of the images present. So the public images are the only spot they are located, not brought in from the resources by gulp at all.

**Comment by Naoray** [comment]
Since the images won't change that often, I don't see the need to include them into the version process.

@austintoddj What do you think?

**Comment by austintoddj** [comment]
@Naoray Agreed. Don't need to include them.

**Comment by austintoddj** [comment]
@Naoray For your `gulpfile.js` merge conflict, just go ahead and update it to include what was merged in #237. 

After that, is it all set to go?

**Comment by Naoray** [comment]
...now the merge conflict should be resolved. However, I did not manage to reslove the loading of the fonts properly.

On the frontend pages this font does not load:
image

And on the Backend this font won't load:
image

The backend thing is loaded somewhere in the `vendor.js`, but I didn't manage to find the issue. Maybe @austintoddj you could take a look into it?

...and I just saw it now... travis is failing :-(. What did I do wrong?

**Comment by Naoray** [comment]
local tests are all working... :/

**Comment by austintoddj** [comment]
@Naoray Hm, here's the first error that pops up for TravisCI:

```
Caused by
exception 'InvalidArgumentException' with message 'File assets/css/backend.css not defined in asset manifest.' in /home/travis/build/austintoddj/canvas/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php:410
```

Does that give you any more insight? I'm assuming the rest are just the same. If you need me to I can pull this down and track down the error too. 

As for the fonts, they were just like the images actually. Should have told  you that. Since the font files were large, I didn't want them to be in two places, so I only put them in the public directory. Does that help?

**Comment by Naoray** [comment]
@austintoddj I guess I was just too dumb to include the ready compiled assets into the PR ;-).

But still this did not resolve the font-not-loading issue. Could you take a look at it?

**Comment by austintoddj** [comment]
@Naoray Yup no problem, I'll take a look and see what I can do! And thanks for all your work on this PR, can't wait to make it a part of the project!

**Comment by Naoray** [comment]
@austintoddj no problem! Was a plessure! I will continue helping to improve canvas!!! :-)

**Comment by austintoddj** [comment]
@Naoray So as far as I can tell, the issue is coming up because all the true application fonts are loaded within `public/fonts`, but now that we are versioning everything, the application is looking into the `build/assets/fonts` directory. So all we'd need to do is get the fonts to that new directory. Does that sound right?

**Comment by nathane** [comment]
Hi, elixir has a `copy` method that you may use to copy files and directories to new locations. All operations are relative to the project's root directory.

```
elixir(function(mix) {
   mix.copy('vendor/foo/bar.css', 'public/css/bar.css') // can can copy a specific file.
         .copy('node_modules/font-awesome/fonts','public/build/fonts') // you can copy an entire directory.
         .copy(['public/css/main.css','public/fonts'], 'public/build'); // you can copy a combination of files and or directories in an array. *Not fully documented, may or may not be fully supported*
});
```


Hope you find this helpful.

Sauce: [Copying files and directories with Elixir](https://laravel.com/docs/master/elixir#copying-files-and-directories) & [Versioning/Cache Busting with Elixir](https://laravel.com/docs/master/elixir#versioning-and-cache-busting)

**Comment by Naoray** [comment]
@nathane thanks, didn't know about the 'combination copying'!

@austintoddj yes, kind of. I forgot that I deleted those font files from the public directory somewhere in the gulp testing process and didn't bring them back in. However, I had to modify 2 scss files which were referencing to the fonts.

@talvbansal I also changed the `gulpfile` that `phpunit` is only run when the `production` flag is set. Hope you don't mind... It was taking ages everytime I ran gulp.

**Comment by austintoddj** [comment]
So the last issue I see with this is that the Media Manager fonts are not being loaded in. @talvbansal Since we are copying your `icomoon` font files and then versioning them, will Media Manager not be able to see them at all? Is there a way around this?

**Comment by austintoddj** [comment]
But as we're pulling in Media Manager as a package, if we just update the css of it, won't that break it when we try to upgrade to the next version @talvbansal? Maybe I'm seeing this whole package deal incorrectly, I thought pulling it in was sort of like the vendor files, which we would never change.

**Comment by Naoray** [comment]
@austintoddj no, you are right!

**Comment by talvbansal** [comment]
@austintoddj you're totally right, short of forking the media manager and bundling it directly into canvas you're unfortunately tied to the paths that it comes with as you would be with any package.

**Comment by austintoddj** [comment]
@talvbansal That's what I thought. No worries.

So with that being said, @Naoray perhaps we move away from versioning the fonts, since we are already not versioning images, and the fonts won't be changing at all. Would you be able to implement that in this PR? Also, as a side note, you can remove the `summernote` fonts, those are old and are not used anymore in the project.

**Comment by Naoray** [comment]
@austintoddj it is not about versioning. The `fonts` are loaded in the `css` - files from `../fonts` and we need them to load from `assets/fonts`

**Comment by austintoddj** [comment]
@Naoray Ah ok. Well, as much as I hate to say it, because of the fact that the package and it's paths are not something that can be manipulated, I would say we keep everything else pure as far as how you've set it up now, and keep the Media Manager fonts where they expect to be. I think that's going to be our cleanest solution. Thoughts?

**Comment by talvbansal** [comment]
@Naoray  aha what your saying is if the media manager them from the document root like `/fonts` rather than a relative path of `../fonts` that will fix that?

If i'm thinking of this right a none breaking change to the media manager so shouldn't be an issue?

**Comment by austintoddj** [comment]
@talvbansal to the rescue. 👍

**Comment by Naoray** [comment]
@talvbansal yes, but in our particular case its from `assets/fonts` :-(

**Comment by talvbansal** [comment]
@Naoray  ahhh i see, im not sure theres a way around this then :(

**Comment by austintoddj** [comment]
@Naoray Ok. Well, back to the original thought, perhaps we just keep media managers fonts in the place it expects them to be?

**Comment by Naoray** [comment]
soo... I think we are ready to merge :+1: 

The thing I changed is simply excluding the media-manage.css and the fonts from the version process.

But in the future we might consider putting those back to the other files... I found [gulp-replace](https://github.com/lazd/gulp-replace), maybe I could build an elixir extension...

**Comment by austintoddj** [comment]
@Naoray One last thing(always one more thing), since the assets in `public` are bundled up nicely in `build` and `assets`, can we remove all the deprecated folders from there? Like the css, fonts, images, js, and vendor?

If so could you submit that as well in this PR? As soon as that's done and you give me the thumbs up I'll merge it.

**Comment by Naoray** [comment]
@austintoddj of cause... was just because I added all files to commit manually. How do you manage your local repositories in git? I get sometimes a bit confused which files to add and which files not to.

**Comment by austintoddj** [comment]
@Naoray Not sure I understand the question actually. Once those folders are removed, I think we should be golden. Could you explain the question one more time?

**Comment by Naoray** [comment]
@austintoddj the folders are removed now.

**Comment by Naoray** [comment]
I normally run `git add .` for adding all changed files to my commit, but when I've run `gulp`, a 'reports' folder will be created, so I've to pay attention to not add this one to my commit. That is why I add every single file with `git add filex` to my commit... it just takes some times and sometimes I miss a few files.

**Comment by austintoddj** [comment]
@Naoray Ah no worries, good call on being careful with git. Ok well I'll go ahead and merge this in now, and release a new version of the app just to make sure everyone gets it properly.

**Pull request merged**
