### PR TITLE
[WIP] Deduce visits from views (#891)

### PR DESCRIPTION
**Pull request by JapSeyz**
Hi,

I marked this as WIP to allow you to play around with it, and see how it works, before we settle on a way to implement it.

Basically it discards the entire `visits` table, and uses the `views` to deduce views.

Views are grouped by Ip, user-agent string and the current date. Meaning one user can create multiple views by jumping IPs, using different browsers or visiting on different days.

I believe the existing setup counts visits the same way, but simply relies on what's in the `visits` table. which can be manipulated by manually removing the Laravel Session, IE. by going Incognito or clearing cookies.

Mainly, this proves to an advantage for users who use Laravel as an API with a separate frontend. See #891

### CODE REVIEW

**Comment by JapSeyz** [comment]
I'll fix the tests and make it behave as expected across scopes, if this is something you're interested in bringing to Canvas.

**Comment by austintoddj** [comment]
Thanks for submitting this @JapSeyz! I'll take a look as soon as I can. Currently moving into a new house this week, so might be just a minute.

**Comment by iMusicJJ** [comment]
No rush! Focus on you first. This is free OSS work, nobody dies if it takes a week or two

**Comment by austintoddj** [comment]
@JapSeyz I appreciate the work that went into this. After reviewing it more, I don't think I want to go this route. Again, thanks for submitting it, I'd be more than happy to look at other PRs if you have other ideas!

**Pull request closed without merging**
