### PR TITLE
Integrate DropzoneJS for file uploads #84

### PR DESCRIPTION
**Pull request by soywod**
So I purpose something about multiple uploads via Dropzone lib.

When click on "upload file" button, a modal appears (the same as before) but now we can drop / select files to upload. Once selected they are automaticly uploaded, so I had to remove the possibility to change file name before upload :/ but I have an idea : what about adding a "edit" button (next to the preview or the trash) to change the name and/or the file itself ?

I need help to refacto the existing upload unit test, now that files are uploaded asynchronously by Dropzone and not via a basic form.

I hope to do well this pull request, let me know if something is wrong or missing !

### CODE REVIEW

**Comment by austintoddj** [comment]
@soywod Thanks for creating this. I'll pull it down and test it out shortly, and let you know if I see anything that should be tweaked.

**Comment by austintoddj** [comment]
@soywod Looks like there are a few conflicts with this branch. Could you remedy those and then I'll keep checking this out? Thanks!

**Comment by soywod** [comment]
It seems to be good, you confirm ? Conflict was on .js.map files, strange ... are they generated with `gulp --production` command ? Or only with `gulp` ?

**Comment by austintoddj** [comment]
Thanks! The assets are always compiled with 'gulp --production'. I'll pull this down shortly.

**Comment by soywod** [comment]
I fixed the new conflict (since laravel shift 5.3), but [this one](https://github.com/austintoddj/canvas/pull/156) must be merged before, then I'll push my fix

**Comment by austintoddj** [comment]
Looks like there are just a few conflicts left with this one @soywod. Would you be able to take a look at them?

**Comment by austintoddj** [comment]
Closed in lieu of #180

**Pull request closed without merging**
