### PR TITLE
Replace Deprecated lists method

### PR DESCRIPTION
**Pull request by talv86**
Laravel 5.3 completely removes the lists method so this quick fix will help for the upgrade later down the line

### CODE REVIEW

**Comment by austintoddj** [comment]
Thanks for getting a lead on this @talv86. I do plan on upgrading to 5.3 soon after it's release, so this is a welcome change. Any other deprecations that you're aware of at this point?

**Comment by talv86** [comment]
I spent a lot of time yesterday looking at changes for Easel, the biggest changes for Canvas will probably be the authentication / login process, I can send the changes that I've made up once you've made a 5.3 branch since the traits the 5.3 auth process uses have changed.

**Comment by austintoddj** [comment]
Like changes as in a breaking change with auth? And yeah, once I've got a branch up and running I'll let you know.

**Comment by talv86** [comment]
nothing major, you cant customise the logout uri anymore so the existing tests will fail, and authentication has been broken up into more sections meaning the current auth traits don't exist. Its really just a case of using the new traits.

**Pull request merged**
