### PR TITLE
Author Popup Overlay

### PR DESCRIPTION
**Pull request by talvbansal**
My attempt at #179

### CODE REVIEW

**Comment by austintoddj** [comment]
@talvbansal Did the last PR I just merged in from you nullify this one?

**Comment by talvbansal** [comment]
Hey! I assumed that the scout PR would eventually be merged so I continued to build on top of it. That's why parts of it may look similar.

I also merged in the latest canvas/master branch changes so that there should be no merge conflicts to resolve if this gets accepted.

**Comment by talvbansal** [comment]
Any update on this? If it's not what you were expecting I can totally revisit it

**Comment by austintoddj** [comment]
@talvbansal Actually haven't had a chance to pull it down yet. I'll hopefully do it today, but the other PR's have kept me occupied. I'll let you know as soon as I take a look though!

**Comment by austintoddj** [comment]
@talvbansal Ok, finally got on top of the issues at hand for the project, now I can review this one quickly. If you get a chance, could you update this PR to fix the conflicts? Thanks! 👍

**Comment by talvbansal** [comment]
Sure take a look now :)

**Comment by austintoddj** [comment]
Hm, getting this error on the frontend

screen shot 2016-11-02 at 8 51 38 am

**Comment by talvbansal** [comment]
What page are you seeing that error on?

I've just pulled in the latest canvas changes to make sure its nothing new that may be causing the change but i still cant find that error.

**Comment by austintoddj** [comment]
@talvbansal Saw this error on the blog index page. Pulled down your branch and re-compiled all the assets and everything.

**Comment by talvbansal** [comment]
Can you try it again now?

**Comment by austintoddj** [comment]
@talvbansal I can in like an hour. I'll let you know what I find.

**Comment by austintoddj** [comment]
Ah ok, it's a browser thing. Try this in Safari, you should see the error. Looks nice in Chrome. That's the idea of what I was going for. If I want to tweak some things and push changes to this branch, am I able to do that?

**Comment by talvbansal** [comment]
I think so tbh i've never done that before.

Also i dont have a mac so i dont know how ill be able to figure this safari bug out, do you know anyone else who may be able to look?

**Comment by talvbansal** [comment]
just had a thought about this try it now...

**Comment by austintoddj** [comment]
@talvbansal Thanks for working on this. Having a change of mind lately and want to figure out a different solution for this and #142. I'll close this out and detail out the new direction in a different Issue. Thanks for doing this though!

**Pull request closed without merging**
