### PR TITLE
Add migrate step on installation processus

### PR DESCRIPTION
**Pull request by welcoMattic**

### CODE REVIEW

**Comment by austintoddj** [comment]
@welcoMattic Thanks for taking the time to contribute to Canvas! As for your PR, the command `canvas:install` actually runs `migrate --seed`, so I'm not sure we need to add an extra step. Granted, it's only 1 extra step, but it's important for me to know why you wanted to add it in. Did you run into a problem during the install?

**Comment by welcoMattic** [comment]
Hello @austintoddj, yes I ran a fresh installation with this problem, migrations has not been run

**Comment by austintoddj** [comment]
Had you utilized the `canvas:install` command? Line 80 should be running it for you so you don't have to. 
screen shot 2016-08-19 at 8 07 47 am

**Comment by welcoMattic** [comment]
Yes, I ran `php artisan canvas:install`, and I had to run migrations from myself

**Comment by austintoddj** [comment]
Interesting. The only way line 80 would be bypassed is if you had already created a user in the database. Had you done that?

**Comment by welcoMattic** [comment]
No, my database was just created seconds before `canvas:install` run. Without any table.
It's very weird :/

**Comment by austintoddj** [comment]
Ok. Appreciate your availability to answer those questions. Let me dig into it today and see what I can find, since that doesn't seem to be appropriate behavior for the application.

**Comment by welcoMattic** [comment]
No problem, if you want more info, ping me here ;)

**Comment by omegachien** [comment]
@austintoddj 
 `$user = User::findOrFail(1);`

image

I will have to change it to `$user = User::find(1);` for it to work.  `findOrFail` will immediately throw an exception when the user is not found right? Since you're checking it with `if(empty($user))`, `User::find(1)` would make sense I suppose :)

**Comment by austintoddj** [comment]
@omegachien @welcoMattic I updated the `canvas:install` command to prevent an exception from being thrown. I'll close this issue out because I can't replicate the error from above. When I follow the `Readme` steps verbatim, I get no errors on any environment. Please open another issue if you continue to have problems. Thanks!

Commit: 8aec7dd3688e93eea13afb99aded1bab6ae915ff

**Pull request closed without merging**
