### PR TITLE
Strip meta data from images to prevent meta data leakage like GPS data

### PR DESCRIPTION
**Pull request by mphill**
People unknowingly update images with GPS data in them. To protect bloggers, remove GPS/meta data from images to avoid potentially revealing their location.

### CODE REVIEW

**Comment by austintoddj** [comment]
Any way we can fix typos where stripe should be strip? Or was that intentional?

**Comment by austintoddj** [comment]
@mphill One thing I would recommend for doing pull requests. Try to make them small and modular, self-contained little fixes that can be pulled in one at a time. When a pull becomes large it can be tough to debug if something goes wrong. Maybe try breaking this one up into a few different ones?

**Comment by mphill** [comment]
Do I need a new branch for each pull request?  I noticed when I committed code, it was automatically being attached to this pull request....

**Comment by austintoddj** [comment]
@mphill I would do a new branch yes. It keeps everything pretty modular. Unless anyone else has a better idea for you.

**Pull request closed without merging**
