### PR TITLE
Added AJAX Request to load repo info

### PR DESCRIPTION
**Pull request by fergthh**
By this way, you would not need to manually update the data as stars, forks or issues.

### CODE REVIEW

**Comment by austintoddj** [comment]
@fergthh You're the man! Thanks for this!

**Comment by austintoddj** [comment]
@fergthh Wonder if you'd take a stab at making the number of downloads work like you did the Github stats. Here is the [documentation](https://packagist.org/apidoc) for the Packagist API, maybe you'd be able to work with that? If so, making it just X.XK would be fantastic, just because there isn't much room on that page for adding extra numbers to that stat.. Let me know what you think!

**Comment by fergthh** [comment]
Yes, I think an excellent idea! :) Let me check the documentation and i
will start to implement it ;)

**Comment by fergthh** [comment]
Done @austintoddj ;)

**Pull request merged**
