### PR TITLE
Keyboard combo to save blog posts whilst writing them

### PR DESCRIPTION
**Pull request by talv86**
Whenever I'm writing a post i'm always hitting Ctrl+s out of habit as if I'm in a word processor. Obviously in a web browser it brings up the save page dialog which isn't whats desired. 

So this small js function looks for form elements with the class "keyboard-save" and will listen for the control+s keyboard combo whenever a child element is in focus and automatically submits the current form.

I've updated the edit and create forms to have the above class.

I also find myself wanting to go back to the main blog list from within the admin section so I just added an additional link that points to "/" in the top right hand main menu!

### CODE REVIEW

**Comment by austintoddj** [comment]
Great idea with this. Thanks for taking the time to contribute. Could you modify your PR to include other forms on the site, such as tag creation/editing, and profile editing? That way every form will have that functionality.

**Comment by talv86** [comment]
no problem ill make the commits now

**Comment by talv86** [comment]
Done!

**Comment by austintoddj** [comment]
Great work! Thanks for doing this. One quick question before merging this in: Apple users will most commonly use command+s to save a document, while PC users will use control+s. Will this allow either of these to work? Just trying to think of all possible scenarios.

**Comment by talv86** [comment]
Good catch! I've updated the code to only listen for cmd+s on a mac and ctrl+s on everything else just tested it on my brothers mac and it works (lucky he has one I only have windows and ubuntu machines).

**Comment by austintoddj** [comment]
Awesome work man! Really appreciate it. Looking forward to whatever else you have to contribute!

**Pull request merged**
