### PR TITLE
Login Section: Added autofocus in email field and show/hide password field button

### PR DESCRIPTION
**Pull request by fergthh**
captura

### CODE REVIEW

**Comment by austintoddj** [comment]
@fergthh What would you think about adding the same password show button to the Profile privacy page? Maybe make it easier for users to edit their passwords?

**Comment by fergthh** [comment]
Yes, sure. The truth is that I had not thought of that, but it would be an
excellent idea. As I return to my house, I add these changes.

**Comment by fergthh** [comment]
@austintoddj Done! Now it is implemented in privacy section too.

**Comment by austintoddj** [comment]
Really like this feature @fergthh. Two questions:

First, could you perhaps change the UI to display either the `zmdi-eye` icon for showing the content, or the `zmdi-eye-off` icon for hidden content instead of the text?

screen shot 2016-07-16 at 11 25 25 pm

Second, on the profile settings page, sometimes when one or two of the inputs is filled in, and I hit the button for hide/show content on any of the inputs, the form will simply submit. Is there any way we can completely make sure the form does not submit unless the actual Submit button is pressed?

**Comment by poklin** [comment]
@austintoddj @fergthh 
I tested with the scripts and found bug.
When I click the "Show content" button, it will automatically submit the request for the privacy tab and also in login.

**Comment by fergthh** [comment]
@poklin Yeah, I am preparing a PR which fix this and adds the @austintoddj
proposals. Thanks for testing.
El 18/07/2016 01:53, "poklin" <notifications@github.com> escribió:

@austintoddj <https://github.com/austintoddj> @fergthh
<https://github.com/fergthh>
I tested with the scripts and found bug.
When I click the "Show content" button, it will automatically submit the
request for the privacy tab and also in login.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/austintoddj/Canvas/pull/51#issuecomment-233228385>, or mute
the thread

**Comment by austintoddj** [comment]
Thanks for helping test with this @poklin.

**Comment by austintoddj** [comment]
@fergthh Any luck making those few changes?

**Pull request merged**
