### PR TITLE
Coauthor

### PR DESCRIPTION
**Pull request by Naoray**
As in #249 described I would love to add "coauthor ability" to canvas.

### CODE REVIEW

**Comment by Naoray** [comment]
@austintoddj how do I fix the stylci things?

**Comment by Naoray** [comment]
@austintoddj ok, won't fix them manually anymore :-P. could you please run this stylci thing? :)

**Comment by talvbansal** [comment]
@Naoray don't worry, they'll get fixed if the PR gets accepted. I have a couple of suggestions however:

- I feel like it'd be nicer if there was a GUI to handle the creation / management of users. A big task maybe that deserves its own PR.
- Currently with this PR a user an only see the posts that they have authored, I think a user should be able to view / edit all posts say for example:
    - User A wants User B to proof a post before putting it live
    - User A wants User B to contribute to a post.
- Given that the current user will always be used in the addAuthor relationship maybe it'd be worth adding a dropdown list of users when the count of users is above one so that a main author can be selected and repopulated when editing a post. In the event that there is only a single user then the current user would be used and the dropdown wouldn't need to be selected

Hope those ideas make sense.

**Comment by Naoray** [comment]
@talvbansal yes, I've also thought about a 'user-management' thing. To include this we should also consider integrating some kind of 'user-rank' system:
- admin (owner of the blog)
- coauthors
-...

But as you already mentioned. What we get with this PR are just the basics. We should make seperate PRs for

- GUI to handle create/management of users
- Contribution Managements to posts (enable co-editing etc.)

Does someone else have suggestions for this coauthor-features?

**Comment by austintoddj** [comment]
@Naoray Thanks for submitting this. I'm taking some time to review it and make sure we cover all our bases. I'll let you know what updates we can do to this.

**Comment by austintoddj** [comment]
@Naoray So I worked hard to take your suggestion but found it easier to re-work everything from the ground up using TDD/BDD. So `v2.1.13` shipped with the user management feature built in, check it out and let me know what you think!

https://github.com/austintoddj/canvas/releases/tag/v2.1.13

**Pull request closed without merging**
