### PR TITLE
Update testing env to use sqlite:memory:

### PR DESCRIPTION
**Pull request by RDelorier**
Just switches the tests to use sqlite in memory database, no need to create a new database and better performance.

Just for reference #20

### CODE REVIEW

**Comment by RDelorier** [comment]
hrmm the travis env vars are overriding the phpunit config

**Comment by erikgall** [comment]
@RDelorier I figured out the problem. Revert your changes to the `.travis.yml` file and add a commit that changes the default value of from `storage_path('database.sqlite')`, to `env('DB_DATABASE', storage_path('database.sqlite')`

**Comment by RDelorier** [comment]
@erikgall it shouldn't need to create a database since its using :memory: but I guess travis doesn't apply environment variables from the phpunit.xml ...

**Comment by RDelorier** [comment]
@erikgall ahh I see now ty

**Comment by erikgall** [comment]
@RDelorier The `DB_DATABASE` environment variable is not used in the sqlite db connection.

**Comment by RDelorier** [comment]
just gonna let that run to make sure it works then I'll clean up these commits lol

**Comment by RDelorier** [comment]
Success! Thanks again @erikgall

**Comment by austintoddj** [comment]
Great work guys! Watching you guys tackle this is pretty sweet. Last question before the merge: if this removes the need for `canvas_testing` like @erikgall implemented earlier, can we remove that section from the readme @RDelorier?

**Comment by erikgall** [comment]
@austintoddj It does..

**Comment by austintoddj** [comment]
Thought so. @RDelorier wanna add that to the commit? Then I'll merge it in.

**Comment by RDelorier** [comment]
Coming right up

**Comment by RDelorier** [comment]
Thanks for this platform @austintoddj , I haven't gotten gotten up the guts to use it yet but I've played around on local and loved it right away. Good luck I'm exited to see how it evolves.

**Comment by austintoddj** [comment]
It's really my pleasure @RDelorier 👍 Thanks for contributing your expertise as much as you have already. It's so great to see everyone come together and work on it like they do. That's why I love the open source world!

**Pull request merged**
