### PR TITLE
Improve assets compilation #67

### PR DESCRIPTION
**Pull request by foxted**
- [x] Compile all assets into a couple files (vendor & app)
- [x] Compile all vendor-related CSS into `public/css/vendor.css`
- [x] Compile all vendor-related JS into `public/js/vendor.js`
- [x] Compile all application-related CSS into `public/css/app.css`
- [x] Compile all application-related JS into `public/js/app.js`
- [x] Assets in `public/` folder generated with `--production` flag

### CODE REVIEW

**Comment by foxted** [comment]
Just rebased this branch if you are interested in merging.

**Comment by austintoddj** [comment]
@foxted Just going to pull this down and take a look at it quickly. Thanks for tackling such a huge portion of this project, I'll merge it in asap once I verify everything looks like it should.

**Comment by foxted** [comment]
No worries, let me know if you have any questions or find any bugs ;)

**Comment by austintoddj** [comment]
No bugs found, thanks for doing this! And after I merge this in, if you ever have any more expertise to offer in the area of LESS/SASS organization or compiling, I welcome the contribution. But thank you for this, I'll merge it in now!

**Comment by foxted** [comment]
I'll see what I can do :)

**Pull request merged**
