### PR TITLE
Fixed fullscreen & side-by-side

### PR DESCRIPTION
**Pull request by fergthh**
Related to @austintoddj [comment](https://github.com/austintoddj/canvas/issues/81#issuecomment-237943391) in #81

### CODE REVIEW

**Comment by austintoddj** [comment]
Thanks @fergthh! You're the man!

**Comment by austintoddj** [comment]
@fergthh Do you think you'd be able to make the right side nav menu pop up in front of the full screen, just to be able to see the menu when in full screen editing mode? Here is the little menu that is behind the full screen:

screen shot 2016-08-06 at 10 10 16 am

**Comment by fergthh** [comment]
Done @austintoddj :+1:

**Comment by austintoddj** [comment]
@fergthh One last z index one for ya. The help button on the new editor pops up a modal guide, which currently sits behind the navbar. Maybe you'd be able to tweak this one as well?

**Comment by fergthh** [comment]
Yes, when I return to my home, I'll take a look ;)

**Comment by austintoddj** [comment]
@fergthh Not to keep piling it on ;) but just got a bug report that ALL modals on the site are behind the navbar, such as on the uploads page. If your solution could include these as well that'd be awesome!

**Pull request merged**
