### PR TITLE
Named Routes for the blog urls

### PR DESCRIPTION
**Pull request by tomschlick**
As mentioned in #167

### CODE REVIEW

**Comment by tomschlick** [comment]
Will fix StyleCI in a few minutes

**Comment by austintoddj** [comment]
@tomschlick Did you want to push the StyleCI fix, or did you just want me to merge it and then fix it?

**Comment by tomschlick** [comment]
I'll take care of it. 

--
Tom Schlick




On Sat, Sep 17, 2016 at 10:53 PM -0400, "Todd Austin" <notifications@github.com> wrote:












@tomschlick Did you want to push the StyleCI fix, or did you just want me to merge it and then fix it?

**Comment by tomschlick** [comment]
Done

**Pull request merged**
