### PR TITLE
Laravel 5.3 Shift

### PR DESCRIPTION
**Pull request by laravel-shift**
This pull request includes the changes for upgrading to Laravel 5.3.

**Before merging**, you should:

- Checkout the `laravel-5.3-shift` branch
- Review **all** pull request comments for additional changes
- Run `composer install`
- Thoroughly test your application

Commit any additional changes to the `laravel-5.3-shift` branch. If there were changes you feel could have been automated, please leave a comment on this pull request to help improve [Laravel Shift](https://laravelshift.com).

### CODE REVIEW

**Comment by laravel-shift** [comment]
I was not able to update your `app/Console/Kernel.php`. You will need to compare yours against the [5.3 version](https://github.com/laravel-shift/laravel-5.3/blob/master/app/Console/Kernel.php) and merge the new changes.

**Comment by laravel-shift** [comment]
Laravel 5.3 no longer includes the `app/Events` folder by default. It is created for you when you make your first *Event* using `artisan`. I did not remove yours as it appears to differ from the default. However, if your app does not use *Events*, you can remove this folder manually to keep your app streamlined.

**Comment by laravel-shift** [comment]
Laravel 5.3 added `Route::auth()` which automatically creates the authorization routes. **Note:** this method registers a `POST` route for `/logout` instead of a `GET` route. If you are using the Authorization component, you should upgrade your code to use this method.

**Comment by laravel-shift** [comment]
Laravel 5.3 split the `Auth/AuthController.php` into the `Auth/LoginController.php` and the `Auth/RegisterController.php`. Since yours appears to be customized, I did not remove it. You should compare your `Auth/AuthController.php` with the newly added controllers and merge your changes accordingly.

**Comment by laravel-shift** [comment]
Laravel 5.3 renamed the `Auth/PasswordController.php` to `Auth/ResetPasswordController.php`. Since yours appears to be customized, I did not remove it. You should compare your `Auth/PasswordController.php` against the added `Auth/ResetPasswordController.php` and merge your changes accordingly.

**Comment by laravel-shift** [comment]
I was not able to update your `app/Providers/AuthServiceProvider.php`. You will need to compare yours against the [5.3 version](https://github.com/laravel-shift/laravel-5.3/blob/master/app/Providers/AuthServiceProvider.php) and merge the new changes.

**Comment by laravel-shift** [comment]
I was not able to update your `app/Providers/RouteServiceProvider.php`. You will need to compare yours against the [5.3 version](https://github.com/laravel-shift/laravel-5.3/blob/master/app/Providers/RouteServiceProvider.php) and merge the new changes.

**Comment by laravel-shift** [comment]
Laravel 5.2 introduced *Middleware Groups*, which are now used in Laravel 5.3. It appears you have not upgraded to *Middleware Groups*. You should review [Middleware Groups](http://laravel.com/docs/5.3/middleware#middleware-groups) in more detail. Then compare your `app/Http/Kernel.php` with the [5.3 version](https://github.com/laravel-shift/laravel-5.3/blob/master/app/Http/Kernel.php) and update manually.

**Comment by laravel-shift** [comment]
Laravel 5.3 now includes a top-level `routes` folder. In addition, it separates routes into *API*, *console*, and *web* files.I have included a default `routes/api.php` and `routes/console.php` as well as migrated your `app/Http/routes.php` to `routes/web.php`. You should review your routes to see if they should be separated into one of the new route files.

**Comment by laravel-shift** [comment]
The default behavior of `Route::resource()` changed in Laravel 5.3. All resource route parameters are now singularized by default and URL prefixes no longer affect the route names.You should review your resource routes and verify this singularized naming will not affect your parameters (or if you were doing this manually, you can remove the `parameter`). In addition, verify you are no longer appending the URI prefix to the route name.

Found `Route::resource()` in:

- [ ] routes/web.php

**Comment by laravel-shift** [comment]
I could not upgrade the following configuration files since they differed from the 5.2 defaults. You need to compare these configuration files against the [Laravel 5.3 configuration files](https://github.com/laravel-shift/laravel-5.3/blob/master/config) and merge any changes:

- [ ] config/auth.php
- [ ] config/cache.php
- [ ] config/database.php
- [ ] config/services.php
- [ ] config/session.php

**Comment by laravel-shift** [comment]
I could not upgrade the following project files since they differed from the 5.2 defaults. You need to compare these project files against the [default Laravel 5.3 versions](https://github.com/laravel-shift/laravel-5.3/) and merge any changes:

- [ ] gulpfile.js
- [ ] package.json

**Comment by laravel-shift** [comment]
Laravel 5.3 has a development dependency for `symfony/css-selector` of `~3.1.*`. You have a modified dependency for `symfony/css-selector` in your `composer.json`. Ensure it meets the new version requirement of `3.1.*`.

**Comment by laravel-shift** [comment]
Laravel 5.3 has a development dependency for `symfony/dom-crawler` of `~3.1.*`. You have a modified dependency for `symfony/dom-crawler` in your `composer.json`. Ensure it meets the new version requirement of `3.1.*`.

**Comment by laravel-shift** [comment]
Laravel 5.3 `where` performs a "loose" comparison. In addition, the *strict* parameter was removed. If you need to perform a "strict" comparison, you can use `whereStrict` instead.

You should review the following usages of `where` to ensure you do not require "strict" compaison:

- [ ] app/Models/Post.php
- [ ] app/Http/Controllers/Backend/ProfileController.php
- [ ] app/Jobs/BlogIndexData.php

**Comment by laravel-shift** [comment]
The Query Builder returns collections, instead of plain arrays, in Laravel 5.3. You will need to upgrade your code to use collections or chain the `all()` method onto your query to return a plain array.

You should review the following usages of Query Builder:

- [ ] database/seeds/UsersTableSeeder.php
- [ ] database/migrations/2016_08_08_231059_create_post_tag_table.php

**Comment by laravel-shift** [comment]
If you are using *Queues*, you no longer need to specify the `--daemon` option when calling the `queue:work`. This is assumed in Laravel 5.3. Use the `--once` option to process a single job.

If you are using the `database` driver, you will need to update your `jobs` and `failed_jobs` table. Review the *Queue* section of the [Laravel 5.3 Upgrade Guide](https://laravel.com/docs/5.3/upgrade#upgrade-5.3.0) for more details.

**Comment by laravel-shift** [comment]
Laravel 5.3 updated several of the default assets as well as adding support for [Vue.js](https://vuejs.org). If you are using Laravel to [compile assets](https://laravel.com/docs/5.3/elixir) you may want to review the latest versions of [`resources/assets/js/app.js`](https://github.com/laravel-shift/laravel-5.3/blob/master/resources/assets/js/app.js) and [`resources/assets/sass/app.scss`](https://github.com/laravel-shift/laravel-5.3/blob/master/resources/assets/sass/app.scss) and update your project accordingly.

**Comment by laravel-shift** [comment]
Laravel 5.3 added configuration for your application name in `config/app.php`. Be sure to set this value as it is used in notifications, like the password reset email.

**Comment by austintoddj** [comment]
@foxted I see that Laravel 5.3 removes the AuthController and PasswordController entirely, splitting them into different ones. Are we able to keep the integrity of our app logic while removing the deprecated classes in this branch?

Also, one of the changes made to the master branch that needs to be carried over to this one is the functionality that allows the app to merely hit the /admin path to login, instead of being redirected to /auth/login. Since that change deals with these files as well, do you have any suggestion on how we can make that work here too?

**Comment by foxted** [comment]
@austintoddj Shouldn't be too much of a problem. Can you tell me more about that /admin displaying the login? I missed that change I think.

**Comment by austintoddj** [comment]
Yup, it just means that for login purposes, I didn't want to be redirected to the default Laravel /auth/login path, just for user-frindlyness purposes. I'd rather the URL path just remain /admin for the login page, and then logging out of course would return us to the login page, at /admin. Does that make sense? If not I can explain it better.

**Comment by foxted** [comment]
So you basically want to use the /admin path for login instead of /auth/login

**Comment by austintoddj** [comment]
Yes that'd be perfect.

**Pull request merged**
