### PR TITLE
Present version as 'UNKNOWN' if not found in database.

### PR DESCRIPTION
**Pull request by lszanto**
Older versions will not have the current_version field in the database so present it as unknown.

### CODE REVIEW

**Comment by jlaswell** [comment]
The latest changes are outside of the scope of the original issue that this is intended to solve. Is there a particular conversation or issue that you're looking to fix? or is this just preference?

**Comment by austintoddj** [comment]
@lszanto Let's try to just solve #194 by stating that the version is older than Canvas 2.1.7 if the value does not exist in the database. Could you refactor this PR?

**Comment by lszanto** [comment]
@austintoddj I've changed it to the specific message however i'm not sure how to remove the user account commits. I forgot to switch to my testing branch.

**Comment by austintoddj** [comment]
Well, there's a few ways you could go about it, but you could just create a new PR with the specific changes, and then I could just close this one out. Your choice.

**Pull request closed without merging**
